// Styles shared by Dialog and AlertDialog (same anatomy in Base UI).
import * as stylex from "@stylexjs/stylex";

import {
  colors,
  fontSizes,
  fontWeights,
  layers,
  lineHeights,
  motion,
  radius,
  shadows,
  space,
  tracking,
} from "../../theme/tokens.stylex.ts";

export const dialogStyles = stylex.create({
  backdrop: {
    backgroundColor: colors.overlay,
    inset: 0,
    opacity: {
      ":is([data-ending-style])": 0,
      ":is([data-starting-style])": 0,
      default: 1,
    },
    position: "fixed",
    transitionDuration: motion.normal,
    transitionProperty: "opacity",
    zIndex: layers.overlay,
  },
  close: {
    position: "absolute",
    right: space.sm,
    top: space.sm,
  },
  description: {
    color: colors.mutedForeground,
    fontSize: fontSizes.md,
    lineHeight: lineHeights.normal,
    margin: 0,
  },
  footer: {
    display: "flex",
    flexWrap: "wrap-reverse",
    gap: space.sm,
    justifyContent: "flex-end",
  },
  header: {
    display: "flex",
    flexDirection: "column",
    gap: space.xs,
    paddingInlineEnd: space.xl,
  },
  popup: {
    backgroundColor: colors.popover,
    borderColor: colors.foreground,
    borderRadius: radius.md,
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: shadows.lg,
    color: colors.popoverForeground,
    display: "flex",
    flexDirection: "column",
    gap: space.lg,
    left: "50%",
    maxHeight: "calc(100dvh - 2rem)",
    maxWidth: "calc(100vw - 2rem)",
    opacity: {
      ":is([data-ending-style])": 0,
      ":is([data-starting-style])": 0,
      default: 1,
    },
    outline: "none",
    overflowY: "auto",
    padding: space.xl,
    position: "fixed",
    top: "50%",
    transform: {
      ":is([data-ending-style])": "translate(-50%, -48%)",
      ":is([data-starting-style])": "translate(-50%, -48%)",
      default: "translate(-50%, -50%)",
    },
    transitionDuration: motion.normal,
    transitionProperty: "opacity, transform",
    transitionTimingFunction: motion.ease,
    width: "32rem",
    zIndex: layers.overlay,
  },
  title: {
    "::before": {
      backgroundColor: "currentColor",
      content: '""',
      flexShrink: 0,
      height: "0.5rem",
      width: "0.5rem",
    },
    alignItems: "center",
    display: "flex",
    fontSize: fontSizes.lg,
    fontWeight: fontWeights.semibold,
    gap: space.sm,
    letterSpacing: tracking.wide,
    lineHeight: lineHeights.tight,
    margin: 0,
    textTransform: "uppercase",
  },
});
